### ISSUE TITLE
Cache too aggressive

### ISSUE THREAD

**Issue by rojepp** [fsprojects/FSharp.Data.SqlClient#128]
The TP caches too aggressively, it does not pick up on changes to the sql schema.

In this recording, I've changed the type of `Avtalskod` in sql. The change isn't picked up automatically, which is to be expected; there is no trigger for it. Then if I try to trigger a change, by adding and removing a space it still doesn't work. But if I leave the space in, then that yields a new cache entry and the change is picked up. So, in order to iterate on my table design, I either have to keep restarting VS or keep disfiguring my sql. :) 
Is this cache needed? Has it had a measurable impact?
If it is really needed, maybe responsiveness could be improved by caching *(per unique set of TP parameters - sql)* just the last sql ? 

![cache](https://cloud.githubusercontent.com/assets/445888/7483699/5cec3e18-f381-11e4-9eed-1c125afe2844.gif)

**Comment by dmitry-a-morozov** [comment]
You won't believe but I spent a whole day today researching on cache improvements for the library.   :)
Currently cache expires in 15 secs.
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/05d411086e76f228fb4d9db21bfa5b6a8719653e/src/SqlClient/ProvidedTypesCache.fs#L10
A way to forcefully refresh it is "Clean" or "Rebuild" commands in Visual Studio.
Cache is unique per single instantiation of SqlCommandProvider. 
A reason I put cache in is because F# tooling tries to acquire same type at least 3 times in a row within very short period of time (less than one second). Which results in 3*n invocations to get metadata from Sql Server unless there is a cache.
```instantiationFunction``` gets invoked 3 times in a row with very same parameters
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/05d411086e76f228fb4d9db21bfa5b6a8719653e/src/SqlClient/SqlCommandProvider.fs#L57

Also keep in mind that I deal with opposite kind of complains - a solution/project that uses library intensively has long compilation time.

All that said, I'm thinking hard about cache improvements.   
If you have any ideas I'm open for discussion.,
//cc @vasily-kirichenko @fsgit

**Comment by rojepp** [comment]
I guess 15 seconds is just long enough to trip me up. :) 
Those 15 seconds is a sliding expiration, so that period became a lot longer for me, because I wouldn't sit still.. 
I didn't bother to check the code before reporting this, but now that I know how it works, I think it's a pretty good solution. Closing this. Thanks for the explanation!

**Comment by vasily-kirichenko** [comment]
I'm against any expiration time for caching at all. In large solutions it increases compilation time significantly.

**Comment by rojepp** [comment]
You'd rather have incorrect results? 
The 15 second sliding expiration shouldn't trip you up if you're compiling a huge solution?

**Comment by vasily-kirichenko** [comment]
I don't know :( Maybe MSSQL DB has something like "schema version" which increases automatically if anything changed?

**Comment by rojepp** [comment]
But then you're round-tripping to database just to check if you should round-trip to database. :) 
Check with Sql Profiler, how often is it really going to db?
