### ISSUE TITLE
Type provider doesn't work when VS launched using a windows user account

### ISSUE THREAD

**Issue by CalvinDale** [fsprojects/FSharp.Data.SqlClient#169]
Is it possible to enable this type provider to run while logged in to Windows using a user account? So far I have found it necessary to log in to Windows using an *Administrator* account or alternatively to log in to Windows using a *User* account and subsequently run Visual Studio as an administrator in order for the `FSharp.Data.SqlClient` type provider to work. Does it really need admin permissions?

**Comment by CalvinDale** [comment]
Interestingly enough I am able to get the same code to work in an `fsx` script file. But in `fs` source code files, I see red squigglies under `SqlCommandProvider` indicating `The type 'SqlCommandProvider' is not defined`, etc.

**Comment by CalvinDale** [comment]
I was eventually able to get this work after a lot of hacking. But I'm not really sure what did the trick. It's nice to know that it is possible to run type providers while logged in using a windows user account. Previously, as an F# newbie, I wasn't sure about that.

**Comment by dmitry-a-morozov** [comment]
Sorry for delayed response - I took a break from computer for weekend.
One thing that comes in mind regarding this issue is usage of integrated security in connection string.
A user account you used to start VS certainly affects the type provider if you have either "Integrated Security=true" or "Trusted_Connection=yes" setting in design time connection string.
