### ISSUE TITLE
Supporting other database engines

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/FSharp.Data.SqlClient#173]
I finally spent some time playing with this project and it's great :-). I inserted a brief mention in the [last module of my F# Data Pluralsight course](https://app.pluralsight.com/library/courses/accessing-data-fsharp-type-providers/table-of-contents).

I'm working with one company and I think the SQL Command provider would be a great fit for them, except that they're using MySQL.

As far as I can see, this is really MS SQL specific at the moment - do you think it would make sense to make the type provider support other database engines? (Provided that there is a way to figure out all the type info that the type provider needs using MySQL...) I guess it would involve adding some sort of abstraction layer - so I wanted to check before trying this (and potentially sending a PR..)

**Comment by dmitry-a-morozov** [comment]
I'm glad you like it ! 
I was pleased to find out that it made to your Pluralsight course. 
It still takes me a lot of effort to maintain this project.

Unfortunately I don't think MySQL support is realistic.
See my answer to Phil's request about Oracle support.
https://github.com/fsprojects/FSharp.Data.SqlClient/issues/157

I think SQLProvider is your the best bet at the moment.

**Comment by tpetricek** [comment]
Yeah, I suspect that getting the info about parameters and result types might be an issue. I started looking at [the MySQL `EXPLAIN` construct](http://dev.mysql.com/doc/refman/5.7/en/explain.html) but that does not seem to be useful.

If there is no way to get the info, then I'd have to do something else (like run the query with sample parameter values and do dynamic reflection...). This would then be quite different than your `SqlCommandProvider` - if I ended up doing that, perhaps it would make sense to keep them in the same project, but have them as separate NuGet packages?

**Comment by dmitry-a-morozov** [comment]
Yep. seems like EXPLAIN is not very helpful. Result set columns types can be probably inferred via something like
```C# 
var reader = command.ExecuteReader(System.Data.CommandBehavior.SchemaOnly);
var dataTable = reader.GetSchemaTable();
```
But it needs to be double check. It depends on ADO.NET MySql provider support. 
Inferring parameters types will be really hard if possible at all.

**Comment by dmitry-a-morozov** [comment]
I'm going to close this. 
I hope you don't feel that I unreasonably refused to accommodate your request.
Another thing I'd like to mention that by rough estimate 70% of codebase in current implementation is Sql Server specific. 
Although reusing 30% of code for other DB vendors seems like right objective it will come at high re-factoring/maintenance price.

**Comment by tpetricek** [comment]
Sounds good, thanks for the detailed info :-) I'm certainly happy to close this!

**Comment by dmitry-a-morozov** [comment]
@tpetricek I could not resist to do some research about MySqlCommand type provider. Technically it should be possible.
There are 2 ADO.NET providers out there: 
1) one from Oracle https://www.nuget.org/packages/MySql.Data/
2) and https://www.devart.com/dotconnect/mysql/components.html

Of course Oracle's version is preferable for many reasons. I only looked at devart because that claim to be able to infer sql statement parameters and their types in MySqlCommandBuilder.DeriveParameters 
https://www.devart.com/dotconnect/mysql/docs/?Devart.Data.MySql~Devart.Data.MySql.MySqlCommandBuilder.html

![image](https://cloud.githubusercontent.com/assets/3004037/11788883/1ba427c4-a248-11e5-8a62-dfe23b37c3e4.png)

But this is not actually accurate. Meaning they know to parse parameter names but give some generic type like VarChar or VarBinary. They have kinda free version of library (Express) https://www.devart.com/dotconnect/mysql/editions.html but it hassle to install and there is no nuget package.

Anyway, key idea that once you have parameter names parsed even with super generic type (like VarBinary) assigned you can infer output resultset column name/types

See both gists below

For oracle provider
https://gist.github.com/dmitry-a-morozov/3e16758c98429afac6fd

For devart
https://gist.github.com/dmitry-a-morozov/34f134ec3191fff471fd

Hope it helps.

**Comment by nojaf** [comment]
Would the newer [MySqlConnector](https://github.com/mysql-net/MySqlConnector) be an option?
It does seem to have a [GetSchemaTable](https://github.com/mysql-net/MySqlConnector/blob/af9c415f777737534f0b77b34df1f34448c859b8/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs#L254) implementation.
