### ISSUE TITLE
Effort to get working on SQL 2008 R2?

### ISSUE THREAD

**Issue by piers7** [fsprojects/FSharp.Data.SqlClient#239]
Hi,

I appreciate this is by design. Looking at the code I can see that the reliance on sp_describe_undeclared_parameters would be a problem, but I'm wondering what the worst case would be if I just typed the parameters as 'obj' in that case.

So before I sink a heap of time into this, do you know if there are any other hard limits preventing working against 2008R2 that you know of? Am tossing up whether to use this or wrap a type provider around Dapper (problem: total inexperience writing type providers).

(sorry, this is more of a discussion than an issue)

**Comment by dmitry-a-morozov** [comment]
The type provider relies on both sp_describe_undeclared_parameters and sys.sp_describe_first_result_set. The second meta-stored procedure can be substituted by ```SET  fmtonly```
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/505ecc77471e9607193c4206a71b1abde975face/src/SqlClient/SqlClientExtensions.fs#L569 with lower quality type inference overall.
 
```sp_describe_undeclared_parameters``` can be hardly replaced. Even if parameter types can be downgraded to ```typeof<obj>```  there is still need to parse number of parameters and their names. 

But there is another very important capability will be missed. Whenever there is a mistake inside T-SQL provider reports something like 
...
Incorrect syntax near ...
The batch could not be analyzed because of compile errors.
...
There is no way to have this on v 2008. 

Considering all above and the fact that 3 major versions of Sql Server have been shopped since 2008 I don't think it's worthwhile and effort to support 2008.

**Comment by piers7** [comment]
Sql 2012 was the first version where Microsoft moved from per-socket licencing to per-core licensing. As a  result for a number of companies that I work with the upgrade was going to cost actual money, rather than be just covered by normal enterprise agreements / Software Assurance. As a result Sql 2008 hangs around a bit longer, especially in the absence of a compelling upgrade case (I know, new features etc..., but if the apps using the database are just treating it as a relational CRUD store then - to be fair - they don't need to pay more to get the same)

For anyone working with SQL 2008 lower type fidelity on the provider in that case will be better than not working at all. Hacking the parameter names out via Regex, and setting them as SqlDbType.Variant seems to be enough to get 'SET FMT ONLY' working (aka CommandBehavior.SchemaOnly). This approach _seems_ to work (as a standalone script).

**Comment by dsevastianov** [comment]
Microsoft doesn't provide mainstream support for 2008 since 2014 and it will stop extended support in 2019. While we understand your pain it is significant effort for us, and we risk to downgrade experience for higher versions as a result.

**Comment by smoothdeveloper** [comment]
@piers7 the runtime support for SQL2008 (2005 even) is there, only you have to work at design time with a more recent version.

**Comment by vasily-kirichenko** [comment]
@piers7 is this still an issue in the year 2018?

**Comment by smoothdeveloper** [comment]
I think we can close this, support of SQL 2008 is there for runtime usage but not for design time.

>  Am tossing up whether to use this or wrap a type provider around Dapper (problem: total inexperience writing type providers).

What would be nice, would be to extract the "sql reflection" logic from this library into a more standalone module / library, that could be used as infrastructure for code generation or analysis outside of the context of the type provider.

**Comment by smoothdeveloper** [comment]
Closing.
