### ISSUE TITLE
Could not load type 'System.Data.SqlClient.SqlConnection' from assembly 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

### ISSUE THREAD

**Issue by albertwoo** [fsprojects/FSharp.Data.SqlClient#322]
### Description
When run: dotnet build. I targeted it to `net471`.
I got below error:
`Could not load type 'System.Data.SqlClient.SqlConnection' from assembly 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.`
But I can use Visual studio MSBuild.exe to build it.
I report this because it breaks my old CI/CD pipeline

### Repro steps

My project is very simple:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Data.SqlClient" Version="2.0.1"/>
    <PackageReference Include="System.Data.SqlClient" Version="4.7.0-preview.18571.3"/>
  </ItemGroup>
</Project>
```
In program file, I just used the SqlCommandProvider for very simple thing, I think it is not related to the issue.

* Operating system: Windows 10
* Database versions: sql server 2017

**Comment by samhanes** [comment]
@albertwoo Did you find a resolution to this issue?

**Comment by smoothdeveloper** [comment]
@albertwoo, it sounds like a binding redirect issue, and to some extent, some flaw in the tooling that added the package references you have.

https://www.nuget.org/packages/FSharp.Data.SqlClient/2.0.1 this version has descriptor for netstandard dependency:

> System.Data.SqlClient (>= 4.5.1) 

It seems to me that nuget is wrongly assuming you are targetting netstandard and added reference to 

```<PackageReference Include="System.Data.SqlClient" Version="4.7.0-preview.18571.3"/>```

Could you remove the version of this one and see how nuget behaves, I'd assume given no other dependencies it would pick v = 4.5.1 since only a single dependency in the graph depends on `System.Data.SqlClient`, but for the given target, this reference shouldn't even exist in the first place.

If this work, I'd try to remove the reference altogether, to target only net471, it shouldn't be needed.

The test projects in this repository have target for net461 and use new SDK, you may look at those for comparison with your project.

If you've figured out the issue, consider adding some details about the fix.

Thanks.

**Comment by albertwoo** [comment]
I used msbuild in visual studio installation folder as a workaround.
