### ISSUE TITLE
Is SqlClient dead? Does contributing make sense?

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharp.Data.SqlClient#385]
I love SqlClient, but I have quite a few issues with it. Most of them I have reported, and some of them I have tried making PRs for.

I see that there has been no commits on `master` for almost a year. Furthermore, there are many PRs (including mine) that have been lying dormant for a long time without being addressed, e.g. #348 and #365 (the latter is even a trivial doc change).

Is this project essentially dead? Does it make sense to take the time to make PRs for this project, or even just post issues?

I'm asking because at this point, part of me is considering simply forking the project and making my own TP inspired by SqlClient which suits my needs and addresses my issues. And that's despite me not knowing the first thing about TP implementations. nor really having the resources to delve into it.

**Comment by smoothdeveloper** [comment]
The death of this project has not been confirmed by Netcraft yet.

Downloads from nuget.org also don't seem to have been drying out.

I guess anyone has their own definition of project death, there are some pending PR that seems to still have activity, I guess on basis of volunteers being able to commit time to push work on those.

**Comment by cmeeren** [comment]
Thanks for responding.

"Dead" wasn't constructive; as you say, anyone can have their own definition that. My definition in this case was whether this project was maintained anymore, or concretely, whether contributing makes sense for us outsiders. My concern was rooted in the lack of any recent response on the issues and PRs I have posted.

We all have lots to do in our lives. I certainly assume that goes for you, too. I respect that, and I'm always fine with a response like "Thanks for the issue/PR, unfortunately I don't have the time to dig into this right now." My concern was that I hadn't received any life sign at all, making me wonder if this project was entirely left by its maintainer(s). That would be a problem since 1) for me there are no alternatives to this TP (it's the only .NET Standard/Core-compatible TP that allows writing raw SQL and call sprocs with TVPs), and there are several issues with SqlClient that are causing me pains. If this project were "dead" in the sense of not being maintained anymore, my only option in getting those errors fixed would be creating and publishing a fork of this project.

I'm glad I was wrong. :)

**Comment by smoothdeveloper** [comment]
@cmeeren I expect that people fixing issues would contribute it in PR, investing in maintaining own fork seems a lot of effort, unless starting a new library from scratch, it never made much sense to me at least.

As I'm not the original author and choices have been made rather conservatively for evolution, I tried to keep the same approach since joining the maintainers, and it may mean additional delay before taking some of the PRs.

If there is any issue with lack of feedback or lagging feedback, the only way is to engage with maintainers, I'm the only active maintainer right now and there is definitely room for more active maintainers, keeping in mind of embracing similar approach wihch worked in establishing this library usage and maintainance so far.

I'm happy to get nudges and overall, more engagement about what users feel about issues/contributions in comments and reactions rather than just sticking with being conservative or just going with my own idea.

**Comment by cmeeren** [comment]
> I'm happy to get nudges and overall, more engagement about what users feel about issues/contributions in comments and reactions rather than just sticking with being conservative or just going with my own idea.

Glad to hear it! I'll continue posting issues and reminders, then. And since I use the library in practically every project I'm responsible for at work and therefore am very invested in SqlClient, feel free to ping me anytime you want a second opinion.

I may also, when time permits (unfortunately it doesn't right now), become more active by contributing PRs, now that I know you're open to that. (The lack of response had me worried).

> I'm the only active maintainer right now

That makes you the boss of the library design. :) I'd say, don't be afraid about not being too conservative. Think about how users are using the library and what kind of design/implementation decisions can best help them. I took over [Elmish.WPF](https://github.com/elmish/Elmish.WPF) framework two years ago and quickly started making some fairly radical changes. For some of the larger or more controversial changes, I posted issues asking for input. Now, a couple of major versions later, I'd say the framework is much more flexible and with much better usability than back then.
