### ISSUE TITLE
Nullable column with SingleRow gives Option<Option<T>>

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/FSharp.Data.SqlClient#68]
If you have a nullable column in the DB and SELECT it with SingleRow = true (assuming you have the appropriate WHERE clause), you get back an Option Option T.

The first Option can be used to determine if the appropriate row was located; the second shows if the column has a value. However, there are times when this distinction is irrelevant and if either the row doesn't exist or the value doesn't exist, you want to get back None, otherwise you want Some T - you don't want to get back Option Option T, but just Option T.

Perhaps an extra argument on the provider definition (or change default behaviour, although I suppose this would be a breaking change) so that in this situation, you get back just Option T.

**Comment by smoothdeveloper** [comment]
I looked at this:

```sql
declare @tsql nvarchar(max) 
set @tsql = 'select getdate()'
exec sp_describe_first_result_set @tsql
set @tsql = 'select getdate() where null = null'
exec sp_describe_first_result_set @tsql
```

is_hidden | column_ordinal | name | is_nullable | system_type_id | system_type_name
------------ | ------------------- | ------- | ------------- | ----------------------- | ----------
0 | 1 | NULL | 0 | 61 | datetime | 8

is_hidden | column_ordinal | name | is_nullable | system_type_id | system_type_name
------------ | ------------------- | ------- | ------------- | ----------------------- | ----------
0 | 1 | NULL | 0 | 61 | datetime | 8

so it currently gives the same type ```DateTime option```

> what if somebody actually cares about difference between absence of row in result set vs null column value?

-- dmitry-a-morozov

@dmitry-a-morozov, API wise it might be better to distinguish this way:

```fsharp
type SingleRowResult<'T> = Record of 'T
                         | NoRecord
```

I find that relying on option type pervasively is not necessarily intent revealing, if user want to distinguish on "absence of row" it would be easier to lookup the code on ```Record``` ```NoRecord```.

With queries above I would expect a ```SingleRowResult<DateTime>```, and when the ````is_nullable``` is true ```SingleRowResult<DateTime option>``` instead of ```DateTime option``` and ```DateTime option option```.
